version: 0.2
phases:
  install:
    commands:
      - echo Installing something
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "Retrieving ECR login password"
      - PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo "Logging into Docker with ECR credentials"
      - REPOSITORY_URI=533267035704.dkr.ecr.us-east-1.amazonaws.com/container-mle
      - docker login --username AWS --password $PASSWORD $REPOSITORY_URI:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=container-mle
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$latest
      - echo Writing image definitions file...
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"533267035704.dkr.ecr.us-east-1.amazonaws.com/container-mle:latest","Update":"true"},"Ports":[{"ContainerPort":8000}]}' > Dockerrun.aws.json
      - cat Dockerrun.aws.json
artifacts:
  files: Dockerrun.aws.json